apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ini.configmap }}
  namespace: {{ .Values.ini.namespace }}
data:
{{- $path := printf "%s/*" .Values.configmapini.path }}
{{ (.Files.Glob $path).AsConfig | indent 2 }}