
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mqsc.configmap }}
  namespace: {{ .Values.mqsc.namespace }}
data:
{{- $path := printf "%s/*" .Values.configmap.path }}
{{ (.Files.Glob $path).AsConfig | indent 2 }}
